// Package main: main cannot be imported, so these tests live beside the unexported run and
// the test helpers the cmd/quarry tests share.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"

	"github.com/koblas/quarry/internal/platform/duckdb"
	"github.com/koblas/quarry/internal/report"
	"github.com/koblas/quarry/internal/store"
	"github.com/koblas/quarry/internal/store/duckstore"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// updateSchemaReference makes the acceptance test rewrite the committed schema reference.
var updateSchemaReference = flag.Bool("update", false, "regenerate plugin/skills/quarry/references/schema.md")

const (
	schemaReferencePath   = "plugin/skills/quarry/references/schema.md"
	findingsParagraphLead = "findings holds"
)

// generateSchemaReference renders the schema reference from the store under home: relations with
// their columns, view comments, the SQL conventions and the findings paragraph, and no row data.
func generateSchemaReference(t *testing.T, home string) string {
	t.Helper()
	schema, err := duckstore.New(storeDirUnder(home)).Schema(t.Context())
	require.NoError(t, err)
	comments := viewComments(t, home)

	var b strings.Builder
	b.WriteString(schemaReferenceHeader(t) + "\n\n")
	b.WriteString("# quarry store schema\n\n")
	b.WriteString("The tables and views `quarry sql` can query, and what their amounts mean.\n\n")
	b.WriteString("## Conventions\n\n" + report.SQLConventions + "\n\n")
	b.WriteString("## Findings\n\n" + findingsParagraph(t) + "\n")
	for _, section := range []struct{ heading, kind string }{{"Tables", store.RelationTable}, {"Views", store.RelationView}} {
		b.WriteString("\n## " + section.heading + "\n")
		for _, rel := range schema.Relations {
			if rel.Kind != section.kind {
				continue
			}
			b.WriteString("\n### " + rel.Name + "\n\n")
			if comment, ok := comments[rel.Name]; ok {
				b.WriteString(comment + "\n\n")
			}
			b.WriteString("| column | type |\n| --- | --- |\n")
			for _, c := range rel.Columns {
				fmt.Fprintf(&b, "| `%s` | `%s` |\n", c.Name, c.Type)
			}
		}
	}
	return b.String()
}

// schemaReferenceHeader is the reference's first line, naming the acceptance test that regenerates it.
func schemaReferenceHeader(t *testing.T) string {
	t.Helper()
	full := runtime.FuncForPC(reflect.ValueOf(Test_skill_schema_reference_matches_the_committed_file).Pointer()).Name()
	name := full[strings.LastIndex(full, ".")+1:]
	return "<!-- Generated by go test ./cmd/quarry -run " + name + " -update; do not edit. -->"
}

// viewComments reads each commented view's COMMENT ON VIEW text from the store under home.
func viewComments(t *testing.T, home string) map[string]string {
	t.Helper()
	db, err := duckdb.OpenReadOnly(t.Context(), filepath.Join(storeDirUnder(home), "quarry.duckdb"))
	require.NoError(t, err)
	t.Cleanup(func() { _ = db.Close() })
	comments := map[string]string{}
	err = db.QueryRows(t.Context(),
		`SELECT view_name, comment FROM duckdb_views() WHERE database_name = current_database() AND schema_name = 'main' AND NOT internal AND comment IS NOT NULL`,
		nil, func(scan func(dest ...any) error) error {
			var name, comment string
			if err := scan(&name, &comment); err != nil {
				return err
			}
			comments[name] = comment
			return nil
		})
	require.NoError(t, err)
	return comments
}

// findingsParagraph is the paragraph of quarry sql's help that describes the findings tables.
func findingsParagraph(t *testing.T) string {
	t.Helper()
	var stdout, stderr bytes.Buffer
	require.Equal(t, 0, run(t.Context(), []string{"sql", "--help"}, &stdout, &stderr), stderr.String())
	for paragraph := range strings.SplitSeq(stdout.String(), "\n\n") {
		if strings.HasPrefix(paragraph, findingsParagraphLead) {
			return paragraph
		}
	}
	require.FailNow(t, "quarry sql --help has no paragraph starting "+findingsParagraphLead)
	return ""
}

func Test_skill_schema_reference_matches_the_committed_file(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	populatedAnalysisStore(t, home)
	got := generateSchemaReference(t, home)
	if *updateSchemaReference {
		require.NoError(t, os.MkdirAll(filepath.Dir(repoRoot+schemaReferencePath), 0o750))
		require.NoError(t, os.WriteFile(repoRoot+schemaReferencePath, []byte(got), 0o600))
	}

	want, err := os.ReadFile(repoRoot + schemaReferencePath)

	require.NoError(t, err, "regenerate with: go test ./cmd/quarry -run Test_skill_schema_reference_matches_the_committed_file -update")
	assert.Equal(t, string(want), got)
}

func Test_skill_schema_reference_names_no_account_category_or_payee(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	populatedAnalysisStore(t, home)
	names := userNames(t, home)

	got := generateSchemaReference(t, home)

	require.Contains(t, names, "Whole Foods", "the store must hold a payee for this pin to bite")
	require.Contains(t, names, "Groceries", "the store must hold a category for this pin to bite")
	require.Contains(t, names, "Old Card", "the store must hold an account for this pin to bite")
	for _, name := range names {
		assert.NotContains(t, got, name)
	}
}

func Test_skill_schema_reference_is_the_same_for_an_empty_store(t *testing.T) {
	populated := t.TempDir()
	t.Setenv("HOME", populated)
	populatedAnalysisStore(t, populated)
	fromPopulated := generateSchemaReference(t, populated)
	empty := t.TempDir()
	t.Setenv("HOME", empty)
	replaceStore(t, empty, store.Rows{})

	fromEmpty := generateSchemaReference(t, empty)

	assert.Equal(t, fromPopulated, fromEmpty)
}

func Test_skill_schema_reference_carries_the_sql_conventions_verbatim(t *testing.T) {
	text := repoFile(t, schemaReferencePath)

	assert.Contains(t, text, report.SQLConventions)
}

func Test_skill_schema_reference_carries_the_findings_paragraph_from_sql_help(t *testing.T) {
	text := repoFile(t, schemaReferencePath)

	assert.Contains(t, text, findingsParagraph(t))
}

func Test_skill_schema_reference_carries_each_view_comment(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	populatedAnalysisStore(t, home)
	comments := viewComments(t, home)
	text := repoFile(t, schemaReferencePath)

	require.Len(t, comments, 5)
	for name, comment := range comments {
		assert.Contains(t, text, "### "+name+"\n\n"+comment+"\n\n")
	}
}

func Test_skill_schema_reference_opens_with_its_regeneration_header(t *testing.T) {
	first, _, _ := strings.Cut(repoFile(t, schemaReferencePath), "\n")

	assert.Equal(t,
		"<!-- Generated by go test ./cmd/quarry -run Test_skill_schema_reference_matches_the_committed_file -update; do not edit. -->",
		first)
}

// userNames lists every account, category (name and full path) and payee name in the store under home.
func userNames(t *testing.T, home string) []string {
	t.Helper()
	db, err := duckdb.OpenReadOnly(t.Context(), filepath.Join(storeDirUnder(home), "quarry.duckdb"))
	require.NoError(t, err)
	t.Cleanup(func() { _ = db.Close() })
	var names []string
	for _, query := range []string{
		`SELECT name FROM accounts`,
		`SELECT name FROM categories UNION SELECT full_path FROM categories`,
		`SELECT name FROM payees`,
	} {
		require.NoError(t, db.QueryRows(t.Context(), query, nil, func(scan func(dest ...any) error) error {
			var name string
			if err := scan(&name); err != nil {
				return err
			}
			names = append(names, name)
			return nil
		}))
	}
	return names
}
